apiVersion: v1
kind: Service
metadata:
  name: mongoservice
  namespace: develop
  labels:
    name: mongoservice
spec:
  ports:
    - port: 27017
      name: mongo
      targetPort: 27017
      protocol: TCP
  clusterIP: None
  selector:
    name: mongoservice
    role: mongo

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongoservice
  namespace: develop
  labels:
    name: mongoservice
spec:
  serviceName: "mongoservice"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        name: mongoservice
    spec:
      securityContext:
        runAsUser: 1000
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--bind_ip"
          - 0.0.0.0
          - "--smallfiles"
          - "--noprealloc"
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: dev
          mountPath: /data/db
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
  volumeClaimTemplates:
  - metadata:
      name: dev
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mongo-kubedevelop"
      resources:
        requests:
          storage: 1Gi

