apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodefrontend
  namespace: develop
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: nodeweb
        image: balipalligayathri/kube-dev:${BUILD_NUMBER}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
