apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mongo-pvc0
 annotations:
   volume.beta.kubernetes.io/storage-class: mongo-storage2
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mongo-pvc1
 annotations:
   volume.beta.kubernetes.io/storage-class: mongo-storage2
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mongo-pvc2
 annotations:
   volume.beta.kubernetes.io/storage-class: mongo-storage2
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 100Mi

