apiVersion: "v1"
kind: Service
metadata:
  name: nodeservice
  labels:
    app: bookstore
spec:
  selector:
    app: bookstore 
  type: NodePort
  ports:
   - port: 90
     name: http
     targetPort: 3000
     nodePort: 30001
     protocol: TCP
